### ISSUE TITLE
你的工具能做到组件化不？

### ISSUE THREAD

**Issue by laden666666** [yubang/applet#1]
能不能做到类似于labrador那种能够做到组件化思想做控件，就是自定义控件，尤其是容器控件？而且这个工具能不能基于npm，感觉是是用python开发的，不知道能不能基于npm？

**Comment by yubang** [comment]
@laden666666 
我这个工具主要是实现一个文件夹（html+css+js）构建成一个页面，一个文件夹（html+css+js）构建组件（可以在页面直接引用），一个路由配置文件来关联url和页面。总的来说就是低门槛的前后端分离的脚手架。因为个人比较熟悉python，所以没有想用nodejs开发一套这样子的工具。
